# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_auto_20160410_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.CharField(max_length=100)),
                ('destination_node', models.CharField(max_length=100)),
            ],
        ),
    ]
