# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_auto_20160413_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node_data',
            old_name='node_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='node_relations',
            old_name='source_node',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='node_relations',
            old_name='destination_node',
            new_name='target',
        ),
    ]
