# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_auto_20160413_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_relations',
            name='value',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
