# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_node_relations_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_data',
            name='group',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='node_relations',
            name='source',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='node_relations',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='node_relations',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
