# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0007_auto_20160413_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_data',
            name='group',
            field=models.IntegerField(),
        ),
    ]
